name: hotel_app_test_exercise
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  carousel_indicator: ^1.0.6
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  http: ^1.1.0
  retrofit: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



flutter:
  uses-material-design: true
  assets:
   - assets/icons/emoji-happy.png
   - assets/icons/close-square.png
   - assets/icons/tick-square.png
  fonts:
    - family: SFProDisplay
      fonts:
      - asset: assets/fonts/SFPRODISPLAYMEDIUM.OTF
